In [9]:
import numpy as np

In [10]:
age_list = [25, 30, 35, 40, 45]
age_array = np.array(age_list)
print(type(age_array))
print(age_array)

<class 'numpy.ndarray'>
[25 30 35 40 45]


In [11]:
print('Shape: ', age_array.shape)
print('Dimensions: ', age_array.ndim)
print('Data type: ', age_array.dtype)
print('Size: ', age_array.size)

Shape:  (5,)
Dimensions:  1
Data type:  int64
Size:  5


In [12]:
a = np.zeros(5)
b = np.ones(5)
c = np.arange(0, 20, 2)
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0  2  4  6  8 10 12 14 16 18]


In [13]:
# matrix = np.array([[[[1, 2], [4, 5], [7, 8]], 
#                    [[1, 2], [4, 5], [7, 8]], 
#                    [[1, 2], [4, 5], [7, 8]]], 
#                    [[[1, 2], [4, 5], [7, 8]], 
#                    [[1, 2], [4, 5], [7, 8]], 
#                    [[1, 2], [4, 5], [7, 8]]]])
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print('Shape: ', matrix.shape)
print('Dimensions: ', matrix.ndim)
print('Data type: ', matrix.dtype)
print('Size: ', matrix.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape:  (3, 3)
Dimensions:  2
Data type:  int64
Size:  9


In [14]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [15]:
matrix = a.reshape(3, 4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
